alias dotgit='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias sq='az account set -s f59139ec-932c-4419-ac4f-b01a05ed5459'
alias gc='git checkout'
alias ga='git add'
alias gr='git remove'
alias gs='git status'
